name: Build API CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Run Build API
      - name: Run Build API
        run: ./gradlew run-build-api

      - name: Sync Repository
        run: |
          git config user.name 'amirisback'
          git config user.email 'faisalamircs@gmail.com'
          git pull
          git commit -am "Update Server API"
          git push