name: Main CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - uses: fwilhe2/setup-kotlin@main
        with:
          install-native: true
      - run: |
          kotlinc-native src/main/kotlin/app/Main.kt